version: "3.4"
services:
  mongo:
    image: "mongo"
    ports:
    - 27017:27017
    volumes:
    - mongodb:/data/db
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
volumes:
   mongodb:
    external:
      name: mongodb
